//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TypingGame.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TypingGame.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aardvark
        ///awesome
        ///automatic
        ///adder
        ///brain
        ///boolean
        ///bummer
        ///balloon
        ///crammed
        ///candid
        ///crawfish
        ///chapter
        ///drawer
        ///dearth
        ///dwarf
        ///dreaded
        ///earned
        ///eased
        ///erased
        ///eradicated
        ///farmer
        ///foolish
        ///faith
        ///funhouse
        ///grime
        ///gainsay
        ///ghoul
        ///grassy
        ///hastily
        ///hashtag
        ///hurler
        ///hammer
        ///icebox
        ///impure
        ///imported
        ///impugn
        ///jewels
        ///jacket
        ///jargon
        ///job
        ///knock
        ///knighted
        ///kosher
        ///kryptonite
        ///loosed
        ///lambda
        ///laborer
        ///laggards
        ///mortar
        ///macaroni
        ///machines
        ///maestros
        ///narcotic
        ///nativity
        ///nauseous
        ///neatness
        ///oafish
        ///oatmeal
        ///obedient
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string challenging {
            get {
                return ResourceManager.GetString("challenging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A
        ///a
        ///aa
        ///aal
        ///aalii
        ///aam
        ///Aani
        ///aardvark
        ///aardwolf
        ///Aaron
        ///Aaronic
        ///Aaronical
        ///Aaronite
        ///Aaronitic
        ///Aaru
        ///Ab
        ///aba
        ///Ababdeh
        ///Ababua
        ///abac
        ///abaca
        ///abacate
        ///abacay
        ///abacinate
        ///abacination
        ///abaciscus
        ///abacist
        ///aback
        ///abactinal
        ///abactinally
        ///abaction
        ///abactor
        ///abaculus
        ///abacus
        ///Abadite
        ///abaff
        ///abaft
        ///abaisance
        ///abaiser
        ///abaissed
        ///abalienate
        ///abalienation
        ///abalone
        ///Abama
        ///abampere
        ///abandon
        ///abandonable
        ///abandoned
        ///abandonedly
        ///abandonee
        ///abandoner
        ///abandonment
        ///Abanic
        ///Abantes
        ///abaptiston
        ///Abarambo
        ///Abaris
        ///abar [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dictionary {
            get {
                return ResourceManager.GetString("dictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ant
        ///apple
        ///ate
        ///art
        ///ball
        ///bail
        ///bunt
        ///boot
        ///car
        ///check
        ///can
        ///cool
        ///dry
        ///draw
        ///drool
        ///den
        ///elk
        ///elm
        ///ear
        ///ease
        ///far
        ///fry
        ///fir
        ///fat
        ///gate
        ///gain
        ///grew
        ///gut
        ///hat
        ///hen
        ///hair
        ///hut
        ///ire
        ///inn
        ///ilk
        ///its
        ///jar
        ///just
        ///jot
        ///jig
        ///kit
        ///kite
        ///kraft
        ///keg
        ///leg
        ///lamb
        ///loom
        ///lore
        ///man
        ///mat
        ///more
        ///mast
        ///name
        ///nail
        ///nut
        ///noose
        ///ore
        ///oats
        ///old
        ///ode
        ///peer
        ///pray
        ///pat
        ///paint
        ///queer
        ///quaint
        ///quip
        ///quo
        ///row
        ///ram
        ///ride
        ///rude
        ///stuck
        ///smear
        ///sand
        ///soon
        ///truck
        ///tab
        ///that
        ///thin
        ///unless
        ///utility
        ///untie
        ///use
        ///wash
        ///war
        ///wham
        ///wharf
        ///xyst
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string easy {
            get {
                return ResourceManager.GetString("easy", resourceCulture);
            }
        }
    }
}
